# Generated by Django 2.2.1 on 2019-07-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField(max_length=100)),
                ('date', models.DateField()),
                ('image', models.ImageField(blank=True, upload_to='photography/')),
            ],
        ),
    ]
