# Generated by Django 3.0.3 on 2020-02-20 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_article'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='article',
            new_name='myquote',
        ),
    ]
