# Generated by Django 2.2.1 on 2019-07-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20190722_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='cell',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='department',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='designation',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='about',
            name='university',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
