# Generated by Django 2.2.1 on 2019-07-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20190722_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(null=True, upload_to='documents/'),
        ),
    ]
