# Generated by Django 2.2.1 on 2019-06-27 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='quote_category',
        ),
    ]
