# Generated by Django 2.2.1 on 2019-06-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_delete_quotecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
